<?php

/** @var \Magento\Framework\View\Element\Template $block */
?>
<p><?= $block->escapeHtml(__('You have signed out and will go to our homepage in 5 seconds.')) ?></p>
<script type="text/javascript">
    localStorage.removeItem("attempts");
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/logout-redirect": {
                "url": "<?= $block->escapeJs($block->escapeUrl($this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl())) ?>"
            }
        }
    }
</script>

