<!--@subject {{trans "AbbottStore Magento Account Deactivation Notice" }} @-->
<!--@vars {
"var name":"Customer Name",
"var url":"Reset Password URL"
} @-->
<p style="font-family:Calibri; font-size:16px;text-transform: capitalize;">Dear {{var name}},</p>

<p style="font-family:Calibri; font-size:16px;">
    Please be advised that your AbbottStore Magento account has been deactivated due to inactivity for the past <b>{{var passwordDeactivateDays}} days</b>.
    If you believe this was done in error or would like to reactivate your account, please contact our Customer Service Team at <b>1-800-258-7677</b> for assistance.
</p>
<!-- End mail body bottom Content -->