<div id="cartupdate-popup" data-backdrop="static" data-keyboard="false" class="modal abbott-modal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close modal-close" aria-label="Close">
                    <span class="sim-icons" data-icon="close"></span>
                </button>
            </div>
            <div class="modal-body">
                <p id="magento-message">Magento Cart Message</p>
                <div class="row mt-4 justify-content-center">
                    <div class="col-8 pt-4">
                        <a id="cart-link" href="#" target="_self" class="btn btn-primary px-4 modal-submit w-100 w-lg-85">Button Text</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
