<?php
/**
 *  @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('pedialyte_header')->toHtml();
?>

<?php
$dataHelper = $this->helper('Abbott\CustomerTransistion\Helper\Data');
$baseURL = $dataHelper->getFailureUrl();
$failureUrl = $baseURL."content/experience-fragments/an/pedialytecom/english/header/checkout/jcr:content/root/header.plain.html?v=".$dataHelper->getAemJsVersion();
$scriptString = <<<script
        require(["jquery","jquery/ui"],function(jQuery) {
        jQuery(document).ready(function() {
            jQuery("#header-set").load("$failureUrl");
        });
    });
    script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
