<?php
    $baseUrl = $this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl();
?>
 <section class="header header__section">
    <header class="pdl-abbott-header abbott-header" id="top">
        <!-- Mobile Menu -->
        <section class="container abbott-header__navbar">
            <div class="row align-items-center">
                <div class="col-8 clearfix position-static">
                    <div class="row">
                        <div class="col-3 col-md-4 abbott-logo">
                            <div class="logo pdl-logo">
                                <a href="<?php echo $baseUrl ?>" target="_self">
                                    <img src="<?php echo $baseUrl.'content/dam/an/pedialytecom/logo-pedialyte.png'?>" alt="pedialyte-logo"/>
				</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </header>
</section>
