<?php
/** @var \Magento\Customer\Block\Newsletter $block */
?>
<?= $block->getChildHtml('form_before') ?>
    <form class="form form-newsletter-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <legend class="legend"><span><?= $block->escapeHtml(__('Manage your contact preferences')) ?></span></legend><br>
            <div id="previousContent">
                <div id="emailSection" class="prefSection">
                    <div id="emailQuestionDiv" class="prefQuestion">
                        <span id="emailLabel">E-mail</span>
                    </div>
                    <div id="emailAnswerDiv" class="prefAnswer">
                        <?php if ($block->getIsSubscribed()) { ?>
                            <span id="emailAnswer"><?= $block->escapeHtml(__('Yes')) ?></span>  
                        <?php } else { ?>
                            <span id="emailAnswer"><?= $block->escapeHtml(__('No')) ?></span>           
                        <?php } ?>
                    </div>
                </div>
                <div class="clr"></div>
            </div>
            <h2 class="changeContentTitle">Change Your Contact Information</h2>
            <div class="field choice">
                <legend class="legend"><span><?= $block->escapeHtml(__('E-mail')) ?></span></legend>
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?= $block->escapeHtmlAttr(__('General Subscription')) ?>"<?php if ($block->getIsSubscribed()) : ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="subscription" class="label"><span><?php echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('abbott_contact_preference')->toHtml();?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary"><button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action save primary"><span><?= $block->escapeHtml(__('Save')) ?></span></button></div>
            <div class="secondary"><a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a></div>
        </div>
    </form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
