<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Sarp2\Block\Checkout\Onepage\Success */

// @codingStandardsIgnoreFile
?>
<?php
    $profiles = $block->getProfiles();
    $profilesCount = count($profiles);
?>
<?php if ($profilesCount > 0): ?>
    <p>
    <?= $block->escapeHtml(__($profilesCount > 1 ? 'Your subscription profiles are' : 'Your subscription profile is') . ':') ?>
    <?php $counter = 0; ?>
    <?php foreach ($profiles as $profile): ?>
        <?php $isLast = ++$counter >= $profilesCount; ?>
        <?php if ($block->getCanViewProfiles()): ?>
            <a href="<?= $block->escapeUrl($block->getViewProfileUrl($profile)) ?>">
                <strong><?= $block->escapeHtml($profile->getIncrementId()) ?></strong>
            </a>
        <?php else :?>
            <?= ' ' . $block->escapeHtml($profile->getIncrementId()) . ($isLast ? '.' : ',') ?>
        <?php endif; ?>
    <?php endforeach; ?>
    </p>
<?php endif; ?>
