<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Magento\Framework\View\Element\Template */

// @codingStandardsIgnoreFile
?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Aheadworks_Sarp2/js/product/braintree/paypal/button-adapter": <?= /* @noEscape */ $block->getViewModel()->getJsonConfig() ?>
        }
    }
</script>
