<!-- This is the subject of the email -->
<!--@subject {{trans "Action Needed to Continue Your Metabolic Formula Orders"}} @-->

<table style="width:100%; font-family:Arial, sans-serif; color:#333; background-color:#f9f9f9; padding:20px;">
    <tr>
        <td>
            <p>Dear {{var customer_name}},</p>
            <p> We are reaching out to inform you that the Metabolic Referral Form/prescription on file for your AbbottStore account will expire soon.</p>
            <p>If you still require this specialty nutrition product and wish to continue ordering through AbbottStore, please have your doctor complete a new form and return it to us via email or fax. A new form can be found at <a href="https://abbottstore.com/">AbbottStore.com</a> on your product’s detail page.</p>
            <p>
                For any further questions, feel free to contact AbbottStore Customer Service at 1-800-258-7677. Our representatives are available Monday through Friday, 9 AM - 6 PM EST.
            </p>
            <p>Thank you for your attention to this matter.</p>
            <p> Sincerely,<br>
                The AbbottStore Team
            </p>
           </td>
    </tr>
</table>