<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Abbott\GigyaIM\Block\Adminhtml\Customer\Edit\Tab\View\GigyaUID
 */
if ($block->isGigyaEnabledForWebsite()) :
    $guid = $block->getGUIDFromParentBlock();
?>
    <tr>
        <th><?php /* @escapeNotVerified */ echo __('Gigya UID:') ?></th>
        <td><?php /* @escapeNotVerified */ echo $guid ? $guid : __('N/A') ?></td>
    </tr>
<?php
endif;
?>
