<?php
/**
 * @var \Magento\Sales\Block\Adminhtml\Order\Create\Coupons $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$helper = $this->helper('Abbott\CartRuleMessage\Helper\Data');
?>


<div class="admin__field field-apply-coupon-code">
    <label class="admin__field-label"><span><?= $escaper->escapeHtml(__('Apply Coupon Code')) ?></span></label>
    <div class="admin__field-control">
        <?php if (!$block->getQuote()->getCouponCode()) : ?>
        <input type="text" class="admin__control-text" id="coupons:code" value="" name="coupon_code" />
            <?= $block->getButtonHtml(__('Apply'), 'order.handleOnclickCoupon($F(\'coupons:code\'))') ?>
        <?php endif; ?>
        <?php if ($block->getQuote()->getCouponCode()): ?>
        <p class="added-coupon-code coupon-code-<?= $escaper->escapeHtml($block->getQuote()->getCouponCode()) ?>">
            <span><?= $escaper->escapeHtml($block->getQuote()->getCouponCode()) ?></span>
            <a href="#" title="<?= $escaper->escapeHtmlAttr(__('Remove Coupon Code')) ?>"
               class="action-remove"><span><?= $escaper->escapeHtml(__('Remove')) ?></span></a>
        </p>
            <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                'onclick',
            "order.removeCoupon('" . $block->getQuote()->getCouponCode() . "');event.preventDefault();",
            'p.added-coupon-code.coupon-code-' . $block->getQuote()->getCouponCode() . ' a.action-remove'
            ) ?>
        <?php
        if($helper->getAdminEnable() && $block->getQuote()->getCouponCode()){
            $message = $helper->getCheckoutMessage($block->getQuote()->getCouponCode());
            if($message){ ?>
                <div class="abbott_custom_checkbox">
                    <input type="checkbox" data-validate="{required:true}" name="custom-message" class="abbott_checkbox">
                    <label for="admin_checkout_message" class="admin_checkout_message"><span><?= $escaper->escapeHtml($message) ?></span></label>
                </div>
            <?php }
        }
        ?>
        <?php endif; ?>
        <?php $isVirtual = ($block->getQuote()->isVirtual() ? 'false' : 'true');
        $scriptString = <<<script
            require([
                "jquery",
                'Magento_Ui/js/modal/alert',
                'mage/translate',
                "Magento_Sales/order/create/form"
            ], function($, alert) {
                order.overlay('shipping-method-overlay', {$isVirtual});
                order.overlay('address-shipping-overlay', {$isVirtual});
                order.handleOnclickCoupon = function (code) {
                    if (!code) {
                        alert({
                            content: $.mage.__('Please enter a coupon code!')
                        });
                    } else {
                        order.applyCoupon(code);
                    }
                };
            });
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
    </div>
</div>
