<?php
    if($this->helper('Abbott\CustomerTransistion\Helper\Data')->getContinueCartShoppingUrl() !== NULL) {
        $contUrl = $this->helper('Abbott\CustomerTransistion\Helper\Data')->getContinueCartShoppingUrl();
    } else {
        $contUrl = $this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl();
    }
?>
<div class="cart-empty">
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <p><?= $block->escapeHtml(__('You have no items in your shopping cart.')) ?></p>
    <p><?= $block->escapeHtml(
        __(
            'Click <a href="%1">here</a> to continue shopping.',
            $contUrl
        ),
        ['a']
    ) ?>
    </p>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Checkout/js/empty-cart": {}
    }
}
</script>
