<?php


namespace Abbott\DPS\Model\ResourceModel;

use Exception;
use Magento\Framework\Model\AbstractModel;
use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class DpsListItem extends AbstractDb
{
    /**
     * Method _construct
     *
     * @return void
     */
    protected function _construct(): void
    {
        $this->_init('abbott_dps_list', 'entity_id');
    }

    /**
     * Method _afterSave
     *
     * @param AbstractModel $object
     * @return DpsListItem
     * @throws Exception
     */
    protected function _afterSave(AbstractModel $object): DpsListItem
    {
        if (count($object->getAddresses())) {
            /** @var \Abbott\DPS\Model\DpsListItemAddress $address */
            foreach ($object->getAddresses() as $address) {
                $address->setParentId($object->getId());
                $address->save();
            }
        }
        return parent::_afterSave($object); // TODO: Change the autogenerated stub
    }
}
