<?php
$is_enable = $this->helper(\Abbott\OrderManagement\Helper\Data::class)->getEnable();
$bufferTime = $this->helper(\Abbott\OrderManagement\Helper\Data::class)->getTime();
$orderManagement = $this->helper(\Abbott\OrderManagement\Helper\Data::class);
$checkoutRestrict = $this->helper(\Abbott\ProgressiveDiscount\Helper\Data::class)->getIsProgressiveCheckoutRestricted();

?>
<?php $_orders = $block->getOrders(); ?>
<?php echo $block->getChildHtml('info'); ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order ID') ?></th>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                    <?php /* @noEscape */ echo $block->getChildHtml('extra.column.header'); ?>
                    <th scope="col" class="col shipping"><?php /* @escapeNotVerified */ echo __('Ship To') ?></th>
                    <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Order Total') ?></th>
                    <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                    <th scope="col" class="col actions"><?php /* @escapeNotVerified */ echo __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Order ID')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?php /* @noEscape */ echo $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?php echo $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $this->helper(\Abbott\OrderManagement\Helper\Data::class)->getOrderStatus($_order->getStatusLabel()) ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <?php
                            $isReorder = 0;
                            $checkProgressiveAndBuyersRemorse = $orderManagement->checkIsProgressiveAndBuyersRemorse($_order->getEntityId());
                            $isProgressiveStatus = isset($checkProgressiveAndBuyersRemorse['is_progressive']) ? $checkProgressiveAndBuyersRemorse['is_progressive'] : "0";
                            $isCancelOrder = isset($checkProgressiveAndBuyersRemorse['is_cancel_order']) ? $checkProgressiveAndBuyersRemorse['is_cancel_order'] : "";
                            if($checkoutRestrict == 1 ){
                                if ($isProgressiveStatus != 1 && $this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId()) && !$this->helper(\Abbott\OrderManagement\Helper\Data::class)->getIsTrial($_order)) {
                                    $isReorder = 1;
                                }
                            }else{
                                if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId()) && !$this->helper(\Abbott\OrderManagement\Helper\Data::class)->getIsTrial($_order)) {
                                    $isReorder = 1;
                                }
                            } ?>
                            <a onclick="orderview()" href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>" class="action view <?php if($isReorder != 1){ echo __('nopipe'); }?>">
                                <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                            </a>
                            <?php if($isReorder == 1):?>
                                <a onclick="reorderview()" href="#" data-post='<?php
                                    /* @escapeNotVerified */ echo
                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                        ->getPostData($block->getReorderUrl($_order))
                                    ?>' class="action order">
                                        <span><?php /* @escapeNotVerified */ echo __('Reorder') ?></span>
                                </a>
                            <?php endif;?>
                            <?php
                              $orderCreatedTime = $_order->getCreatedAt();
                              $currentTime = $this->helper(\Abbott\OrderManagement\Helper\Data::class)->getCurrentDate();
                              $timeDiffInSeconds = strtotime($currentTime) - strtotime($orderCreatedTime);
                            ?>
                            <?php

                            if ($is_enable == 1 && ($_order->getStatusLabel() == 'Pending' || $_order->getStatusLabel() == 'Processing') && $timeDiffInSeconds < $bufferTime) : ?>


                             <?php if($isProgressiveStatus == 1) : ?>
                                  <?php if($isCancelOrder == 1) : ?>
                                        <a href="javascript:void(0);" class="cancel-<?php echo $_order->getRealOrderId() ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span>
                                            </a>
                                  <?php endif;?>
                             <?php else:?>

                                     <a href="javascript:void(0);" class="cancel-<?php echo $_order->getRealOrderId() ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span>
                                        </a>
                             <?php endif;?>


                                <div style="display:none;" class="popup-form-<?php echo $_order->getRealOrderId() ?>">
                                    <form class="form cancel-order-<?php echo $_order->getRealOrderId() ?>"
                                          action="<?php /* @escapeNotVerified */ echo $this->helper(\Abbott\OrderManagement\Helper\Data::class)->getFormAction($_order); ?>"
                                          method="post">
                                        <div class="fieldset">
                                            <div class="field note no-label order-q"><?php /* @escapeNotVerified */ echo __('Are you sure you want to cancel this order?') ?><br>
                                                <span class="order-id"><?php /* @escapeNotVerified */ echo __('Order #') ?><?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?></span></div>
                                        </div>
                                    </form>
                                </div>
                                <script type = 'text/javascript'>
                                    require(
                                            [
                                                'jquery',
                                                'Magento_Ui/js/modal/modal'
                                            ],
                                            function (
                                                    $,
                                                    modal
                                                    ) {
                                                var options = {
                                                    type: 'popup',
                                                    buttons: [{
                                                            text: $.mage.__('Yes'),
                                                            class: 'btn-yes',
                                                            click: function () {
                                                                $('.cancel-order-<?php echo $_order->getRealOrderId() ?>').submit();
                                                            }
                                                        }, {
                                                            text: $.mage.__('No'),
                                                            class: 'btn-no',
                                                            click: function () {
                                                                this.closeModal();
                                                            }
                                                        }]
                                                };

                                                var popup = modal(options, $('.popup-form-<?php echo $_order->getRealOrderId() ?>'));
                                                $(".cancel-<?php echo $_order->getRealOrderId() ?>").on('click', function () {
                                                    $(".popup-form-<?php echo $_order->getRealOrderId() ?>").modal("openModal");
                                                });

                                            }
                                    );
                                </script>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no orders.'); ?></span></div>
            <?php endif ?>
<div class="order_history_return_note"><strong>Need to return an item?</strong> Select to view the order.</div>
<script>
function orderview()
{
window.dataLayer = window.dataLayer || [];
window.dataLayer.push({event: "ga-custom-events",eventCategory: "view-order",eventAction: "click",eventLabel: "view-order"});
}

function reorderview()
{
window.dataLayer = window.dataLayer || [];
window.dataLayer.push({event: "ga-custom-events",eventCategory: "re-order",eventAction: "click",eventLabel: "re-order"});
}
</script>
