<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Sarp2\Block\Customer\Subscriptions\Edit\Plan */

// @codingStandardsIgnoreFile
?>
<?php
    $profile = $block->getProfile();
    $savePlanTitle = __('Save Subscription');
?>
<form class="form validate page-products"
      action="<?= $block->escapeUrl($block->getSaveUrl($profile->getProfileId())) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <div class="products-grid">
    <ol class="product-items">
        <?php foreach ($profile->getItems() as $item): ?>
            <?php if (!$item->getParentItemId()): ?>
                <li class="product-item">
                    <?php if ($block->isProductExists($item->getProductId()) && $block->hasProductUrl($item->getProductId())): ?>
                        <a class="product-item-photo" href="<?php echo $block->escapeUrl($block->getProductUrl($item->getProductId())) ?>">
                            <div class="product product-item-image">
                                <?php /* @noEscape */ echo $block->getProductImageHtml($item->getProductId()); ?>
                            </div>
                            <a href="<?php echo $block->escapeUrl($block->getProductUrl($item->getProductId())) ?>">
                                <span><?php echo $block->escapeHtml($item->getName()) ?></span>
                            </a>
                        </a>
                        <?php
                        $product = $block->getProduct($item->getProductId());
                        $itemId = $item->getItemId();
                        ?>
                        <!--<div class="options">
                            <fieldset class="fieldset">
                                <?php if ($product->isSaleable()): ?>
                                    <?php if ($product->isVisibleInSiteVisibility()): ?>
                                        <div class="field qty">
                                            <label class="label" for="qty[<?= $block->escapeHtmlAttr($itemId) ?>]">
                                                <span><?= $block->escapeHtml(__('Qty')) ?></span>
                                            </label>
                                            <div class="control">
                                                <input type="number"
                                                       data-role="qty"
                                                       id="qty[<?= $block->escapeHtmlAttr($itemId) ?>]"
                                                       class="input-text qty"
                                                       data-validate="{'required-number':true,'validate-greater-than-zero':true}"
                                                       name="qty[<?= $block->escapeHtmlAttr($itemId) ?>]"
                                                       value="<?= /* @noEscape */ (int)($item->getQty() * 1) ?>">
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($product->getIsSalable()): ?>
                                        <p class="available stock"
                                           title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                        </p>
                                    <?php else: ?>
                                        <p class="unavailable stock"
                                           title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                        </p>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </fieldset>
                        </div>-->
                    <?php else: ?>
                        <?php echo $block->escapeHtml($item->getName()) ?>
                    <?php endif; ?>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ol>
    </div>
    <div class="aw-sarp2-product-subscription-options">
        <div class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <div class="field subscription-type<?= $block->hasOptions() ? ' options-margin' : ''; ?>">
                <div class="control">
                    <div class="nested options-list"
                         data-role="aw-sarp2-subscription-type"
                         data-mage-init='{"awSarp2SubscriptionOptionList":{
                        "defaultValue": <?= /* @noEscape */ \Zend_Json::encode($block->getDefaultOptionId()) ?>
                     }}'
                    >
                        <?php foreach ($block->getOptionArray() as $optionId => $optionLabel): ?>
                            <?php $htmlId = 'aw-sarp2-subscription-option-' . $optionId ?>
                            <div class="field choice">
                                <input type="radio"
                                       class="radio product option"
                                       data-validate="{'validate-one-required-by-name':true}"
                                       id="<?= /* @noEscape */ $htmlId ?>"
                                       name="aw_sarp2_subscription_type"
                                    <?php if ($block->getDefaultOptionId() == $optionId): ?>
                                        checked="checked"
                                    <?php endif ?>
                                       value="<?= /* @noEscape */ $optionId ?>"
                                       aria-required="true">
                                <label class="label" for="<?= /* @noEscape */ $htmlId ?>">
                                    <span><?= $block->escapeHtml($optionLabel) ?></span>
                                </label>
                            </div>
                        <?php endforeach; ?>
                        <div class="block subscription-details" data-role="aw-sarp2-subscription-details">
                            <div class="block block-title">
                                <strong><?php echo $block->escapeHtml(__('Subscription details')) ?></strong>
                            </div>
                            <div class="block block-content">
                                <div class="subscription-details_inner">
                                    <ul data-role="aw-sarp2-subscription-details-list" class="subscription-details-list">

                                    </ul>
                                </div>
                            </div>
                            <script data-role="details-item-template"
                                    type="text/x-magento-template">
                                <li>
                                    <div class="details-field"><%- label %></div>
                                    <div class="details-value"><%- value %></div>
                                </li>
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <button type="submit"
            class="action primary"
            title="<?= $block->escapeHtml($savePlanTitle) ?>">
        <span><?= $block->escapeHtml($savePlanTitle) ?></span>
    </button>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Aheadworks_Sarp2/js/product/config/provider": {
                "config": <?= /* @noEscape */ $block->getConfigData() ?>
            },
            "Aheadworks_Sarp2/js/product/config/provider/generic-providers": {}
        }
    }
</script>
