<?php $addressHelper = $this->helper(\Magento\Customer\Helper\Address::class);
      $address = $block->initAddressObject($block->getPublicHash());
      $cardLast = $block->getCardDetails($block->getPublicHash());
      $isEdit = 0;
      $displayClass = '';
      $configPath = 'general/region/display_all';
?>

<div id="cc-form-bt">
  <form data-mage-init='{"validation":{}}' id="hosted-fields-form" method="post" class="similac_form_anim">
    <fieldset class="fieldset" style="float:none;">
        <legend class="legend"><span><?= $block->escapeHtml(__('Billing Information')) ?></span></legend><br>
        <div class="required_note">* Required</div>
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getNameBlockHtml() ?>
        <div class="field fet company">
            <label class="label" for="company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
            <div class="control">
                <input type="text" name="company" id="company" value="<?= $block->escapeHtml($block->getAddress()->getCompany()) ?>" title="<?= $block->escapeHtml(__('Company')) ?>" class="input-text"/>
            </div>
        </div>
        <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>
        <div class="field fet street required">
            <label for="street_1" class="label"><span>Street Address</span></label>
            <div class="control">
                <input type="text" name="street" value="<?= $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="street_1" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>" required/>
            </div>
        </div>
        <div class="field fet city required">
            <label class="label" for="city"><span>City</span></label>
            <div class="control">
                <input type="text" name="city" value="<?= $block->escapeHtml($block->getAddress()->getCity()) ?>" title="city" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city') ?>" id="city"/>
            </div>
        </div>
        <div class="field fet select region required">
            <label class="label" for="region_id"><span>State</span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="state" class="validate-select region_id" <?= (!$block->getConfig($configPath)) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="region" title="state" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region') ?>"<?= (!$block->getConfig($configPath)) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="field fet zip required">
            <label class="label" for="zip"><span>Zip</span></label>
            <div class="control">
                <input type="text" value="<?= $block->escapeHtml($block->getAddress()->getPostcode()) ?>" name="postcode" title="zip" id="zip" class="input-text validate-zip-international <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode') ?>" required/>
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
        <div class="field fet select country required">
            <label class="label" for="country"><span>Country</span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <div class="field fet telephone">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Telephone')) ?></span></label>
            <div class="control">
                <input type="text" value="<?= $block->escapeHtml($block->getAddress()->getTelephone()) ?>" name="telephone" title="<?= $block->escapeHtml(__('Phone Number')) ?>" class="input-text" id="telephone"/>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset" data-bind="scope:'btHosted'">
      <div data-bind="afterRender: initHostedFields">
        <legend class="legend"><span><?= $block->escapeHtml(__('Card Information')) ?></span></legend><br>
        <?php if ($block->getPublicHash()) {
              $isEdit = 1;
              $displayClass = 'd-none';
            ?>
          <div class="field select-action required">
              <label class="label" for="select-action">Select Card</label>
              <div class="control">
                  <select id="address-or-both" name="address-or-both" title="state">
                    <option value="continue"><?= /* @noEscape */ $block->escapeHtml(__('Continue using card XXXXXX-')).$cardLast ?></option>
                    <option value="update"><?= /* @noEscape */ $block->escapeHtml(__('Update Credit Card Details')) ?></option>
                  </select>
              </div>
          </div>
        <?php } ?>

        <div id="credit-card-details" class="<?= /* @noEscape */ $displayClass ?>" >
          <div class="field type">
              <div class="control">
                  <ul class="credit-card-types">
                      <!-- ko foreach: {data: getCcAvailableTypes(), as: 'item'} -->
                      <li class="item" data-bind="css: {
                          _active: $parent.selectedCardType() == item,
                          _inactive: $parent.selectedCardType() != item
                      } ">
                          <!--ko if: $parent.getIcons(item) -->
                          <img data-bind="attr: {
                              'src': $parent.getIcons(item).url,
                              'width': $parent.getIcons(item).width,
                              'height': $parent.getIcons(item).height
                          }"
                          alt="ct">
                          <!--/ko-->
                      </li>
                      <!--/ko-->
                  </ul>
              </div>
          </div>
          <label for="card-number">Credit Card Number</label>
          <div id="card-number">
            <div id="card-number-error" class="card-error-text"></div>
          </div>
          <label for="expiration-date">Expiration Date</label>
          <div id="expiration-date">
            <div id="expiration-date-error" class="card-error-text"></div>
          </div>
          <label for="cvv">Card Verification Number</label>
          <div id="cvv">
            <div id="cvv-error" class="card-error-text"></div>
          </div>
        </div>
      </div>
      <?= $block->getChildHtml('form.my.credit.card.recaptcha') ?>
      <button id="save-card" type="submit" disabled>Save Changes</button>
      <p class="back-link">
        <a href="<?= /* @noEscape */ $block->getUrl('vault/cards/listaction') ?>"><small></small>Cancel</a>
      </p>
    </fieldset>
  </form>
</div>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ ($block->getConfig($configPath) ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#hosted-fields-form",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        },
        "#cc-form-bt": {
          "Magento_Ui/js/core/app" : {
            "components" : {
              "btHosted" : {
                "component" : "Abbott_CreditCards/js/view/bthosted",
                "at" : "<?= /* @noEscape */ $block->getAT() ?>",
                "getSuccessUrl" : "<?= /* @noEscape */ $block->getUrl('vault/cards/listaction') ?>",
                "isEdit" : "<?= /* @noEscape */ $isEdit ?>",
                "paymentToken" : "<?= /* @noEscape */ $block->getPublicHash() ?>",
                "icons" : <?= /* @noEscape */  $block->getIcons() ?>,
                "btConfig" : <?= /* @noEscape */  $block->getBraintreeConfig() ?>
              }
            }
          }
        }
    }
</script>
