<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/** @var $block \Aheadworks\Sarp2\Block\Adminhtml\Subscription\Info\NextOrderInfo */

// @codingStandardsIgnoreFile
$profile = $block->getCurrentProfile();
 
?>
<div class="next-order-info">
    <table class="admin__table-secondary next-order_details">
        <tbody>
            <tr>
                <th class="next-order_title">
                    <span class="title"><?= $block->escapeHtml(__('Next Order')) ?></span>
                </th>
                <td><?= /* @noEscape */ $block->getNextOrderDateInfo() ?></td>                 
            </tr>
             
            <tr>
                <th class="next-order_title">
                    <span class="title"><?= $block->escapeHtml(__('Order Total (excl. tax)')) ?></span>
                </th>
                <td><?php /* @noEscape */ echo $block->formatProfileAmount($block->getNextPaymentAmountHtml() * $profile->getItemsQty(), $profile->getBaseCurrencyCode()) ?></td>

            </tr>
            <?php if ($block->isMembershipModelEnabled()): ?>
                <tr>
                    <th class="membership-paid-until">
                        <span class="title"><?= $block->escapeHtml(__('Membership is Paid Until')) ?></span>
                    </th>
                    <td colspan="2"><?= /* @noEscape */ $block->getMembershipPaidDateInfo() ?></td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
