<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/** @var $block \Aheadworks\Sarp2\Block\Adminhtml\Subscription\Info\NextOrderAndPlan */

// @codingStandardsIgnoreFile
?>
<?php
    $profile = $block->getProfile();
    $planDefinition = $profile->getProfileDefinition();
?>
<section class="admin__page-section next-order-and-plan">
    <?= $block->getNextOrderInfoHtml() ?>
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Subscription Plan')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <div class="admin__page-section-item-title">
                <span class="title">
                    <a href="<?php echo $block->escapeUrl($block->getPlanEditUrl($profile->getPlanId())) ?>"><?php echo $block->escapeHtml($profile->getPlanName()) ?></a>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary subscription-plan_details">
                    <tbody>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Number of Payments')) ?>:</th>
                            <td>
                                <?php if ($planDefinition->getTotalBillingCycles() > 0): ?>
                                    <?php /* @noEscape */ echo $planDefinition->getTotalBillingCycles() ?>
                                <?php else: ?>
                                    <?php echo $block->escapeHtml(__('Infinite')) ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Repeat')) ?>:</th>
                            <td><?php echo $block->escapeHtml($block->formatRepeatValue($profile)) ?></td>
                        </tr>
                        <tr>
                            <?php
                                $orderAdminDate = $block->formatDate(
                                    $block->getAdminDate($profile->getStartDate()),
                                    \IntlDateFormatter::MEDIUM
                                );
                            ?>
                            <th><?php echo $block->escapeHtml(__('Start')) ?>:</th>
                            <td><?php /* @noEscape */ echo $orderAdminDate ?></td>
                        </tr>
                        
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Each Payment (excl. tax)')) ?>:</th>
                            <td><?php /* @noEscape */ echo $block->formatProfileAmount($block->getNextPaymentAmountHtml() * $profile->getItemsQty(), $profile->getBaseCurrencyCode()) ?></td>
                            
                        </tr>
            
                      
                        <?php if ($planDefinition->getIsTrialPeriodEnabled() && $profile->getTrialSubtotal()): ?>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Trial Period')) ?>:</th>
                                <td><?php echo $block->escapeHtml(__($planDefinition->getTrialTotalBillingCycles() > 1 ? '%1 payments' : '%1 payment', $planDefinition->getTrialTotalBillingCycles())) ?></td>
                            </tr>
                        <?php endif; ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Qty')) ?>:</th>
                            <td><?php echo floatval($profile->getItemsQty()); ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>