<?php
/**
 * $block Abbott\ValidateAdminPassword\Block\Adminhtml\User\Validate
 */
$password_lenght = $block->getPasswordLength();
?>
<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/translate'
    ], function($){
        $.validator.addMethod(
            'abbott-validate-admin-password', function (v) {
                var pass;
                if (v === null) {
                    return false;
                }
                pass = $.trim(v);
                if (pass.length === 0) {
                    return true;
                }
                if (!/[a-z]/i.test(v) || !/[0-9]/.test(v)) {
                    return false;
                }
                if (pass.length < <?= $password_lenght; ?>) {
                    return false;
                }
                return true;
            },
            $.mage.__('Please enter ' + <?= $password_lenght; ?>  +
                '  or more characters, using both numeric and alphabetic.')
        );

        $.validator.addMethod(
            'abbott-validate-cpassword', function (v) {
                var pass;
                if (v === null) {
                    return false;
                }
                pass = $.trim(v);
                if (pass.length === 0) {
                    return true;
                }
                var orgPassword = $("#user_password").val();
                if (pass != orgPassword) {
                    return false;
                }
                return true;
            },
            $.mage.__('Please make sure your passwords match')
        );
    });
</script>
