<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
/* @var $block \Aheadworks\Sarp2\Block\Customer\Subscriptions\Edit\View\PaymentDetails\Type\OfflinePaymentDefault */
/* @var $paymentMethod \Magento\Payment\Model\MethodInterface */
?>

<div class="payment-details wrapper">
    <div class="payment-method-title">
        <span><?= $block->escapeHtml($paymentMethod->getTitle()) ?></span>
    </div>
</div>
