<?php

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$abbottHelper = $this->helper('Abbott\Backorder\Helper\Data');
$productUrl = $this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl().''.$this->helper('Abbott\MyAccount\Helper\Data')->getAemUrl($_item->getProductId());
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()) : ?>
        <a href="<?= $productUrl ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else :?>
            <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
        </a>
    <?php else :?>
        </span>
    <?php endif; ?>
        <div class="product-item-details item-<?= $block->escapeHtmlAttr($_item->getId()) ?>-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $productUrl ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else :?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if($abbottHelper->getBackorderStatus($product) && $abbottHelper->getStatus('backorder')){ ?>
                <p class="backorder_text">Backorder</p>
            <?php } ?>

            <?php if($product->getResource()->getAttribute('flavors')->getFrontend()->getValue($product) && $abbottHelper->getStatus('falvour')){ ?>
                <p class="flavour_text">Flavor: <?= $product->getResource()->getAttribute('flavors')->getFrontend()->getValue($product);?></p>
            <?php } ?>

            <?php if($product->getResource()->getAttribute('size')->getFrontend()->getValue($product) && $abbottHelper->getStatus('size')){ ?>
                <p class="size_text">Size: <?= $product->getResource()->getAttribute('size')->getFrontend()->getValue($product);?></p>
            <?php } ?>
            <?php if ($_options = $block->getOptionList()) :?>
                <dl class="item-options">
                    <?php $tempoption = [];
                    foreach ($_options as $_option) :?>
                        <?php if ($block->escapeHtml($_option['label']) == 'First payment' || $block->escapeHtml($_option['label']) == 'Trial payment(s)' || $block->escapeHtml($_option['label']) == 'Regular payments') {
                            continue;
                        }
                        $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                            <?php else :?>
                                <?= $block->escapeHtml($_formatedOptionValue['value'], ['span']) ?>
                            <?php endif;
                            if ($block->escapeHtml($_option['label']) == 'Billing Period') { ?>
                                <br><span>Repeats until failed or canceled</span>
                            <?php } ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()) :?>
                <?php foreach ($messages as $message) :?>
                    <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>

    <?php if ($canApplyMsrp) :?>
        <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else :?>
        <td class="col price abbott_price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty abbott_qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <div class="control qty custom-qty ">
                <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                    <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                    <div class="qty_bar">
                        <a href="javascript:void(0)" data-id="<?= /* @escapeNotVerified */ $_item->getId() ?>" id="<?= /* @escapeNotVerified */ $_item->getId() ?>-dec" data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" class="ajax_qty ajax_qty_dec ajax-cart-qty-minus decreaseQty qty_button">-</a>
                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               type="number"
                               min="1"
                               size="4"
                               step="any"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty qty_val"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-item-qty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               data-role="cart-item-qty"/>
                        <a href="javascript:void(0)" data-id="<?= /* @escapeNotVerified */ $_item->getId() ?>" data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" id="<?= /* @escapeNotVerified */ $_item->getId() ?>-upt" class="ajax_qty ajax_qty_inc ajax-cart-qty-plus increaseQty qty_button">+</a>
                    </div>
                </label>
            </div>
        </div>
    </td>

    <td class="col subtotal abbott_subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp) :?>
            <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
    <td class="col del" colspan="4">
        <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
</tbody>
<script type="text/x-magento-init">
    {
        "*": {
            "Abbott_Checkout/js/cartjs": {},
            "Abbott_Checkout/js/updatejs": {}
        }
    }
</script>
