<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Sarp2\Block\Product\SubscriptionOptions */

// @codingStandardsIgnoreFile
?>
<div class="aw-sarp2-product-subscription-options">
    <div class="fieldset">
        <div class="field subscription-type<?= $block->hasOptions() ? ' options-margin' : ''; ?>">
            <div class="control">
                <div class="nested options-list"
                     data-role="aw-sarp2-subscription-type"
                     data-mage-init='{"awSarp2SubscriptionOptionList":{
                        "defaultValue": <?= /* @noEscape */ \Zend_Json::encode($block->getDefaultOptionId()) ?>
                     }}'
                >
                    <?php foreach ($block->getOptionArray() as $optionId => $optionLabel): ?>
                        <?php $htmlId = 'aw-sarp2-subscription-option-' . $optionId ?>
                        <div class="field choice">
                            <input type="radio"
                                   class="radio product option"
                                   data-validate="{'validate-one-required-by-name':true}"
                                   id="<?= /* @noEscape */ $htmlId ?>"
                                   name="aw_sarp2_subscription_type"
                                <?php if ($block->getDefaultOptionId() == $optionId): ?>
                                    checked="checked"
                                <?php endif ?>
                                   value="<?= /* @noEscape */ $optionId ?>"
                                   aria-required="true">
                            <label class="label" for="<?= /* @noEscape */ $htmlId ?>">
                                <span><?= $block->escapeHtml($optionLabel) ?></span>
                            </label>
                        </div>
                    <?php endforeach; ?>
                    <div class="block subscription-details" data-role="aw-sarp2-subscription-details">
                        <div class="block block-title">
                            <strong><?php echo $block->escapeHtml(__('Subscription details')) ?></strong>
                        </div>
                        <div class="block block-content">
                            <div class="subscription-details_inner">
                                <ul data-role="aw-sarp2-subscription-details-list" class="subscription-details-list">

                                </ul>
                            </div>
                        </div>
                        <script data-role="details-item-template"
                                type="text/x-magento-template">
                            <li>
                                <div class="details-field"><%- label %></div>
                                <div class="details-value"><%- value %></div>
                            </li>
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "awSarp2RegularPrice": {},
            "awSarp2ElementVisibility": {
                "elementSelector": "[data-role=aw-sarp-product-subscribe-button]",
                "eventName": "updateSubscriptionOptionValue",
                "eventTarget": "[data-role=aw-sarp2-subscription-type]"
            }
        },
        "*": {
            "Aheadworks_Sarp2/js/product/config/provider": {
                "config": <?= /* @noEscape */ $block->getConfigData() ?>
            },
            "Aheadworks_Sarp2/js/product/config/provider/generic-providers": {}
        }
    }
</script>
