<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/** @var $block \Aheadworks\Sarp2\Block\Adminhtml\Product\SubscriptionOptions\Notice */

// @codingStandardsIgnoreFile
?>
<label class="admin__field-label"></label>
<div class="admin__field-control">
    <span>
        <?php /* @noEscape */ echo __('If children products have their own prices, they will override these settings.') ?>
    </span>
</div>
