<?php
/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl().'etc.clientlibs/abbott/clientlibs/clientlib-glucerna.min.css'?>">
<?php
    $baseUrl = $this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl();
    $glucernaStoreLibsUrl = $baseUrl.'etc.clientlibs/abbott/clientlibs/clientlib-glucerna.min.js';
?>
<?php $scriptString = <<<script
    require(["jquery","js/jquery.cookie.min"],function(jQuery) {
        $ = jQuery;
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
<script type="text/x-magento-init">
{
    "*": {
        "<?php echo $glucernaStoreLibsUrl ?>": ""
    }
}
</script>
