<link rel="stylesheet" type="text/css" href="<?php echo $this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl().'etc.clientlibs/an/similac/clientlibs/clientlib-similac-base.min.css'?>">
<link rel="stylesheet" type="text/css" href="<?php echo $this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl().'etc.clientlibs/an/similac/clientlibs/clientlib-similac-commons.min.css'?>">

