<?php 
/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('glucerna_footer')->toHtml();

$dataHelper = $this->helper('Abbott\CustomerTransistion\Helper\Data');
$viewModelCookiePref = $block->getData('cp_view_model');
$cmId = $viewModelCookiePref->getCmId();
?>
<input type="hidden" id="cmpidField" name="cmpid" value="<?php echo $cmId;?>">
<?php
    $failureUrl = $dataHelper->getFailureUrl() . '_jcr_content/root/footer.html';
    $scriptString = <<<script
    require(["jquery","jquery/ui"],function(jQuery) {
        jQuery(document).ready(function() {
            jQuery( "#footer-set" ).load("$failureUrl");
        });
    });
    script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>