<?php
/**
 *  @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

    echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('abbott_header')->toHtml();

$baseUrl = $this->helper('Abbott\CustomerTransistion\Helper\Data')->getFailureUrl();
$abbottStoreLibsUrl = $baseUrl.'etc.clientlibs/abbott/clientlibs/clientlib-abbottstore.min.js';

?>

<?php
$failureUrl = $baseUrl."_jcr_content/root/header.html";
$scriptString = <<<script
        require(["jquery","jquery/ui"],function(jQuery) {
        jQuery(document).ready(function() {
            jQuery("#header-set").load("$failureUrl");
        });
    });
    script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Theme/js/clientlib-abbottstore": {
                "src": "<?= $abbottStoreLibsUrl ?>"
            }
        }
    }
</script>
