<div class="top-blue-subhead">Congratulations!</div>
<div class="checkout-success">
  <div class="box">
    <p class="thank-you-title">Thanks for your order!</p>
    <p class="confirmation-email-text">You will receive a confirmation<br class="break-at-media">e-mail &amp; shipment notification.</p>
  </div>
  <div class="order-info-text">
    <?php if ($block->getOrderId()) :?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p><?= $block->escapeHtml(__('Your order number is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif;?>
    <?php endif;?>
  </div>
  <div class="track-order">
      <p><a href="<?php echo $block->getUrl("sales/order/history/") ?>" class="go-to-link">Go to</a> your account to track your order.</p>
  </div>
</div>
