<?php
/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Form\Account
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="admin__page-section-title <?= $block->escapeHtmlAttr($block->getHeaderCssClass()) ?>">
    <span class="title"><?= $block->escapeHtml($block->getHeaderText()) ?></span>
    <div class="actions"></div>
</div>
<div id="customer_account_fields" class="admin__page-section-content">
    <?= $block->getForm()->getHtml() ?>
</div>
<?php $scriptString = <<<script
    require(["prototype", "Magento_Sales/order/create/form"], function(){
        order.accountFieldsBind($('customer_account_fields'));
        var emailflagstore = order.flagstore;
        var similac_store_id = order.similac_store_id;
        if((order.storeId == similac_store_id) && (emailflagstore)){
            if(jQuery("#email").val())
            {
                jQuery("#email").attr('readonly','readony');
            }
		}
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
