<?php
/* @var $block \Aheadworks\Sarp2\Block\Checkout\Onepage\Success */

// @codingStandardsIgnoreFile
?>
<?php
    $profiles = $block->getProfiles();
    $profilesCount = count($profiles);
    $profileHistoryDataHelper = $this->helper(\Abbott\Subscriptionhistory\Helper\Data::class);
?>
<?php if ($profilesCount > 0): ?>
  <div class="subscription-success">
    <p>Your subscription payment profiles:</p>
    <p>
    <?= $block->escapeHtml(__($profilesCount > 1 ? 'Your subscription profiles are' : 'Your subscription profile number is') . ':') ?>
    <?php $counter = 0; ?>
    <?php foreach ($profiles as $profile): ?>
        <?php $isLast = ++$counter >= $profilesCount; ?>
        <?php if ($block->getCanViewProfiles()): ?>
            <a href="<?= $block->escapeUrl($block->getViewProfileUrl($profile)) ?>">
                <strong><?= $block->escapeHtml($profile->getIncrementId()) ?></strong>
            </a>
        <?php else :?>
            <?= ' ' . $block->escapeHtml($profile->getIncrementId()) . ($isLast ? '.' : ',') ?>
        <?php endif; ?>
        <?php if($profileHistoryDataHelper->getSubscriptionHistoryStatus($profile->getStoreId())){ 
				$profileHistoryDataHelper->setProfileHistoryData($profile->getProfileId());		
		}?>
    <?php endforeach; ?>
    </p>
  </div>
<?php endif; ?>
