<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Sarp2\Block\Customer\Subscriptions\Edit\View */

// @codingStandardsIgnoreFile
?>
<?php
$profile = $block->getProfile();
$minQty = null;
$maxQty = null;
$shippingAddress = $profile->getShippingAddress();
$productId = null;
$profileItemCount = count($profile->getItems());
$customerTransitionHelper = $this->helper(\Abbott\CustomerTransistion\Helper\Data::class);
$accountHelper = $this->helper(\Abbott\Sarp2\Helper\Data::class);
$profileHistoryHelper = $this->helper(\Abbott\Subscriptionhistory\Helper\HistoryMessages::class);
$profileHistoryData = $profileHistoryHelper->getSubscriptionHistoryData($profile->getProfileId());
foreach ($profile->getItems() as $item) {
    $productId = $item->getProductId();
    break;
}
if ($productId) {
    $productData = $block->getProfileProduct($productId);
}
if ($productData) {
    $minQty = $productData->getData('cans_y_min_update');
    $maxQty = $productData->getData('cans_x_max_update');
}
?>
<div class="table-wrapper aw-sarp2-customer-subscriptions edit_customer_subscription_table">
    <table class="data table">
        <tbody>
            <tr>
                <th><?php echo $block->escapeHtml(__('Product Name')) ?></th>
                <td class="col products">
                    <ul>
                        <?php foreach ($profile->getItems() as $item): ?>
                            <?php if (!$item->getParentItemId()): ?>
                                <li>
                                    
                                        <?php echo $block->escapeHtml($item->getName()); ?>  
										
                                        <div class="subscription_product_actions">
										
										<?php if($block->isProductExists($item->getProductId()) && !empty($accountHelper->getChangeProductUrl($profile->getStoreId(), $profile->getPlanId(), $profile->getId(), $item->getSku()))){ ?>
                                            <a class="change_product" href="<?php echo $customerTransitionHelper->getFailureUrl().$accountHelper->getChangeProductUrl($profile->getStoreId(), $profile->getPlanId(), $profile->getId(), $item->getSku()); ?>"><?php echo $block->escapeHtml(__('Change Product')); ?></a>
										<?php } ?>   
										<?php if($block->isProductExists($item->getProductId()) && !empty($accountHelper->getChangeProductUrl($profile->getStoreId(), $profile->getPlanId(), $profile->getId(), $item->getSku())) && !empty($accountHelper->canRemoveProduct($profile->getPlanId(), $profileItemCount))){ echo __(' / '); } ?>
                                             <?php if($block->isProductExists($item->getProductId()) && !empty($accountHelper->canRemoveProduct($profile->getPlanId(), $profileItemCount))){ ?>
											 
                                               <a data-role="aw-sarp2-remove-button-<?php echo $item->getProductId(); ?>" class="aw-sarp2-remove-button" onclick="deleteTrackingNumber('<?= $block->escapeUrl($accountHelper->getRemoveProductUrl($profile->getProfileId(), $item->getSku())) ?>','<?= $block->escapeJs($block->escapeHtml(__('Remove Product'))) ?>','<?= $block->escapeJs($block->escapeHtml(__('Are you sure you want to remove this product from subscription?'))) ?>'); return false;" href="#"><?php echo $block->escapeHtml(__('Remove Product')); ?></a>
                                        <?php } ?>
                                        </div>
                                </li>
                            <?php endif;?>
                        <?php endforeach;?>
                    </ul>
                </td>
                <td>
                    
                </td>
            </tr>
            <tr>
                <th><?php echo $block->escapeHtml(__('Subscription Schedule')) ?></th>
                <td><?php echo $block->escapeHtml($block->getPlanName($profile)) ?></td>
                <td>
                    <?php if($block->isEditPlanActionAvailable($profile->getProfileId())): ?>                      
					   <a href="<?php echo $block->escapeUrl($block->getSubscriptionPlanEditUrl($profile->getProfileId())) ?>"
                           class="action aw-sarp2__subscription-plan">
                            <span><?php echo $block->escapeHtml(__('Edit')) ?></span>
                        </a>
                    <?php endif;?>
                </td>
            </tr>
            <tr>
                <th><?php echo $block->escapeHtml(__('Next Payment Date')) ?></th>
                <td><?php /* @noEscape */echo $block->getNextPaymentDateInfo($profile) ?></td>
                <td>
                    <?php if ($block->isEditNextPaymentDateActionAvailable($profile->getProfileId())): ?>
                        <a href="<?php echo $block->escapeUrl($block->getNextPaymentDateEditUrl($profile->getProfileId())) ?>"
                           class="action aw-sarp2__next-payment-date">
                            <span><?php echo $block->escapeHtml(__('Edit')) ?></span>
                        </a>
                    <?php endif;?>
                </td>
            </tr>
            <tr>
                <th><?php echo $block->escapeHtml(__('Shipping Address')) ?></th>
                <td>
                    <?php if ($shippingAddress && !$profile->getIsVirtual()): ?>
                        <?=/* @noEscape */$block->getFormattedAddress($shippingAddress)?>
                    <?php endif;?>
                </td>
                <td>
                    <?php if ($block->isEditAddressActionAvailable($profile)): ?>
                        <a href="<?php echo $block->escapeUrl($block->getShippingAddressEditUrl($profile->getProfileId())) ?>"
                           class="action aw-sarp2__shipping-address">
                            <span><?php echo $block->escapeHtml(__('Edit')) ?></span>
                        </a>
                    <?php endif;?>
                </td>
            </tr>
            <tr>
                <th><?php echo $block->escapeHtml(__('Payment Details')) ?></th>
                <td>
                    <?=/* @noEscape */$block->getPaymentDetailsHtml($profile)?>
                </td>
                <td>
                    <?php if ($block->isEditActionAvailable($profile->getProfileId())): ?>
                        <a href="<?php echo $block->escapeUrl($block->getPaymentDetailsEditUrl($profile->getProfileId())) ?>"
                           class="action aw-sarp2__payment-details">
                            <span><?php echo $block->escapeHtml(__('Edit')) ?></span>
                        </a>
                    <?php endif;?>
                </td>
            </tr>
            <?php if ($profile->getStoreId() == 3){
             foreach($profile->getItems() as $item){
                ?>
            <tr>
                <th><?php echo $block->escapeHtml(__('Quantity')) ?></th>
                <td>
                    <a id="minus" href="#">-</a>
                    <input type="text" class="taxtcansQtytxt" id="cansQtytxt_<?php echo $item->getItemId(); ?>" readonly="true" size="3" value="<?php echo floatval($profile->getItemsQty()) ?>" />
                    <a id="plus" href="#">+</a>
                    <br/>
                    <span>
                    <?php if ($minQty && $maxQty): ?>
                        Min: <?=$minQty?>, Max: <?=$maxQty?>
                    <?php endif;?>
                    </span>
                </td>
                <td>
                        <a href="javascript:void(0);" id="saveQtyLink_<?php echo $item->getItemId(); ?>"
                           class="action edit_qty">
                            <span><?php echo $block->escapeHtml(__('Save')) ?></span>
                </td>
            </tr>
            <?php }  } else {

            foreach($profile->getItems() as $item){
            ?>
            <tr>
                <th><?php echo $block->escapeHtml(__('Quantity')) ?></th>
                <td>
                <span><?php echo $item->getName(); ?></span>
                    <input type="text" class="taxtcansQtytxt" id="cansQtytxt_<?php echo $item->getItemId(); ?>" size="3" value="<?php echo floatval($item->getQty()) ?>" />

                </td>
                <td>
                    <a href="javascript:void(0);" id="saveQtyLink_<?php echo $item->getItemId(); ?>"
                           class="action edit_qty">
                            <span><?php echo $block->escapeHtml(__('Save')) ?></span>
                </td>
            </tr>
            <?php }  } ?>
        </tbody>
    </table>
    <div class="subscription_cancel_btn">
        <?php if ($block->isCancelActionAvailable($profile->getProfileId())): ?>
            <a data-role="aw-sarp2-cancel-button" href="#"
               class="action cancel" onclick="deleteTrackingNumber('<?= $block->escapeUrl($block->getCancelUrl($profile->getProfileId())) ?>','<?= $block->escapeJs($block->escapeHtml(__('Cancel Subscription'))) ?>','<?= $block->escapeJs($block->escapeHtml(__('Are you sure you want to cancel this subscription?'))) ?>'); return false;">
                <span><?php echo $block->escapeHtml(__('Cancel Subscription')) ?></span>
            </a>
        <?php endif;?>
    </div>
    <?php if($profileHistoryHelper->getSubscriptionHistoryStatus($profile->getStoreId()) && !empty($profileHistoryData)){ ?>
        <div class="table-wrapper edit_customer_subscription_history">
            <div class="page-title-wrapper aw-sarp2__title">
                <h1 class="page-title">
                    <span class="base" data-ui-id="page-title-wrapper"><?php echo $block->escapeHtml(__('Subscription History')) ?></span>    
                </h1>            
            </div>
            <table class="data table" id="profile_history">
                <tbody>
                <?php foreach($profileHistoryData as $data): ?>
                    <?php echo html_entity_decode(htmlentities($profileHistoryHelper->getDataChanged($data, true))); ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <!-- For Pagination -->
        <?php if ($block->getPagerHtml()) : ?>
                <div class="order-products-toolbar toolbar bottom">
                    <?= $block->getPagerHtml() ?>
                </div>
        <?php endif ?>
	<?php } ?>
</div>
<script type="text/javascript">
require([ 'jquery', 'domReady!', 'mage/cookies'], function($){
    var valueElement = $('.taxtcansQtytxt');
    function incrementValue(e){
        var canX = "<?php echo $minQty; ?>";
        var canY = "<?php echo $maxQty; ?>";
        var incremetnVal = Math.max(parseInt(valueElement.val()) + e.data.increment, 0);
        if(parseInt(incremetnVal) < parseInt(canX)){
            return false;
        }
        if(parseInt(incremetnVal) > parseInt(canY)){
            return false;
        }
        valueElement.val(incremetnVal);
        return false;
    }
    $('#plus').bind('click', {increment: 1}, incrementValue);
    $('#minus').bind('click', {increment: -1}, incrementValue);

    $(".edit_qty").click(function(){
        var alink = $(this).attr('id');
        var itemId = alink.split('_')[1];
        var itemQty =  $('#cansQtytxt_' + itemId).val();
        if(itemQty <= 0)
        {
            alert('Please enter valid Qty'); return;
        }
        $('body').trigger('processStart');
        $.ajax({
        url : '<?php echo $block->getUrl("awsarp2/subscription/update"); ?>',
        type : 'POST',
        showLoader: true,
        data: {
            profile_id: '<?php echo $profile->getProfileId()?>',
            profileItemId: itemId,
            qty: itemQty,
            impUsr: $.mage.cookies.get('mage_usr_imp'),
			form_key: $.mage.cookies.get('form_key')
        },
        dataType:'json',
            success : function(data) {
                $('body').trigger('processStop');
                if(data.success!=false && $('#profile_history').css('display') == "block"){
                    var msg = data.success;
                    console.log(msg);
                    msg = msg.slice(1, -1 );
                    console.log(msg);
                    $('#profile_history > tbody:last-child').append('<tr><td>'+msg+'</td></tr>');
                }
            },
            error : function(request,error)
            {
            }
        });
    });
});
</script>
<script type="text/javascript">
require(['jquery', 'Magento_Ui/js/modal/confirm'], function($, confirmation) {
	'use strict';

function deleteTrackingNumber(url, titleLabel, confirMessage) {
console.log(url);
console.log('click remove product');
 window.dataLayer = window.dataLayer || [];
 if(titleLabel != "Cancel Subscription"){
 window.dataLayer.push({
            event: "ga-custom-events",
            eventCategory: "edit-subscription",
            eventAction: "click",
            eventLabel: "remove-product"
        });
 }
    confirmation({
        title: titleLabel,
        content: confirMessage,
        actions: {
            confirm: function() {
                // do something when the confirmation button is clicked
				 console.log(url);
                    $.ajax({
                        url : url,
                        type : 'POST',
                        showLoader: true,
                        data: {
                        profile_id: '<?php echo $profile->getProfileId()?>',
                        form_key: $.mage.cookies.get('form_key')
                        },
                        dataType:'json',
                        success : function(data) {
                            //$('body').trigger('processStop');
                            console.log('cancel subscription log');
                            console.log(data);
                            if(data.success == true){
                                if(titleLabel == "Cancel Subscription"){
                                    window.location.href = "<?php echo $block->getUrl('aw_sarp2/profile'); ?>";
                                } else {
                                    window.location.href = "<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>";
                                }
                            }
                            
                        },
                        error : function(request,error)
                        {
                            console.log(error);
                        }
                    });
            },
            cancel: function() {
                // do something when the cancel button is clicked
            },
            always: function() {
                // do something when the modal is closed
            }
        },
        buttons: [{
            text: $.mage.__('No'),
            class: 'action-secondary action-dismiss',
            click: function (event) {
                this.closeModal(event);
            }
        }, {
            text: $.mage.__('Yes'),
            class: 'action-primary action-accept',
            click: function (event) {
                this.closeModal(event, true);
            }
        }]
    });
}
window.deleteTrackingNumber = deleteTrackingNumber;
});
</script>
